[build]
  publish = "dist"

[dev]
  targetPort = 5173
  publish = "dist"

[[redirects]]
from = "/api/*"
to = "https://api.hubapi.com/:splat"
status = 200
force = true
[redirects.headers]
Access-Control-Allow-Origin = "*"
Authorization = "Bearer pat-eu1-eb6d47e7-af77-4bc4-b0a5-d96219bc645b"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200